backend:
  name: git-gateway ## (Когда сайт на Netlify с включённой Identity + Git Gateway)
  ## name: test-repo ## Когда ты тестируешь локально и не настроен GitHub
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
    fields:
  - { label: "ID", name: "id", widget: "hidden" }
  - { label: "Title", name: "title", widget: "string" }
  - { label: "URL", name: "url", widget: "string" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Author", name: "author", widget: "string" }
  - { label: "Keywords", name: "keywords", widget: "string" }
  - { label: "Description", name: "description", widget: "text" }
  - { label: "Cover Image", name: "image", widget: "image" }
  - { label: "Alt Text", name: "alt", widget: "string" }
  - { label: "Content", name: "body", widget: "markdown" }
